### ISSUE TITLE
Why generate "https://searchengineland.com/" the Feed to be wrong？

### ISSUE THREAD

**Issue by hardway120308** [zhengchun/feedocean#2]
Screenshot：

![feedocean-sel-issues-1](https://user-images.githubusercontent.com/38828904/43913253-2c636854-9c37-11e8-914b-de65b5e4e0ff.png)
![feedocean-sel-issues-2](https://user-images.githubusercontent.com/38828904/43913252-2c3179ca-9c37-11e8-9052-2f9b459a030b.png)

**Comment by zhengchun** [comment]
Because `https://searchengineland.com/` page response a `content-type` header  is incorrect.

Already fixed. try again.
